# Generated by Django 3.2.5 on 2021-07-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rams',
            name='capacidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rams',
            name='formato',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rams',
            name='frecuencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rams',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rams',
            name='voltateje',
            field=models.CharField(max_length=50),
        ),
    ]
