# Generated by Django 3.2.5 on 2021-07-08 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210707_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('procesador', models.CharField(max_length=60)),
                ('memoria', models.CharField(max_length=60)),
                ('graficos', models.CharField(max_length=80)),
                ('almacenamiento', models.CharField(max_length=50)),
                ('caratula', models.ImageField(null=True, upload_to='games')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marca')),
            ],
        ),
    ]
