# Generated by Django 3.2.5 on 2021-07-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gabinete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('nucleos', models.CharField(max_length=50)),
                ('socket', models.CharField(max_length=50)),
                ('cache', models.CharField(max_length=50)),
                ('arquitectura', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='procesadores')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marca')),
            ],
        ),
    ]
